apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry
  namespace: default
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
      delete:
        enabled: true
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    auth:
      token:
        # external url to docker-web authentication endpoint
        realm: http://localhost:8080/api/auth
        # should be same as registry.name of registry-web
        service: localhost:5000
        # should be same as registry.auth.issuer of registry-web
        issuer: 'my issuer'
        # path to auth certificate
        rootcertbundle: /etc/docker/registry/auth.cert
  auth.cert: |
    -----BEGIN CERTIFICATE-----
    MIIE+zCCAuOgAwIBAgIJAIDbOpAN0RRjMA0GCSqGSIb3DQEBCwUAMBQxEjAQBgNV
    BAMMCWxvY2FsaG9zdDAeFw0xODAzMjEwODQ3NTVaFw0xOTAzMjEwODQ3NTVaMBQx
    EjAQBgNVBAMMCWxvY2FsaG9zdDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
    ggIBAMbCFtmzwxttVkXUHcxNfvrVwvrflNgjrhxZAz3WM0j+hob9AzlCoUwpuQxG
    ZHxnLhFpUfZXkz13S6y4JozI53DZcVhB2KIfb5FZ77taEOOF/yx1tmmUAO0UWASK
    0hyfKeSe4vnVEOCk3NgalB54b0YMycsmg/TPyhYjdvzAwexUENxdEGzgZBXO8MEe
    ILWdMj0S8w+FmZ2X5h+bOmMc/WV3xvh+4FRYf9XvezBrGw8MNliNL3XdA93EycMK
    Oe2/2uabOWtP+9raKIMLMeZLwfSfJ7XcU5VdIScpYd12P9u+DLbnVDJpEMOtO7vb
    4Hhffqsy5WEhmDWNy7C2K+3PacyRLAKbVPe/wFqkLeP/IbEqzOhcB7DpPMjIcJ45
    gaWUu3YWAn5vxmVl9GT69H0f8ta0ZIn42i+I2Rfb57/ELFmFyr2nsIzd13KPuX9g
    h/mSZQj+JNfv9WdO2cLyTNAT7k+AOTe4iHYQmdQ/x+2TQ7Tk+g/UviPx4rQkQ4zx
    W8+TiS3y+xTgT60udhbrd+l2wv95MjnAVxiGBTth17Ek9NbyoYZyIamlsjz9D2j1
    8KmHPL4JQ0zr9bKki9QFfJgFhkbUS9H2zinSGiSFVCdpUojREDog6TgxFKe/ZP0p
    9VofiRn19XTIiVN9GoalJ/N/RK4dMB0dhpQr1mdBHXPh8YcNAgMBAAGjUDBOMB0G
    A1UdDgQWBBQbhgz+EaiI++zIDCCiL/xypJ1LaTAfBgNVHSMEGDAWgBQbhgz+EaiI
    ++zIDCCiL/xypJ1LaTAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4ICAQAg
    +sawJm3+k9SpDU5/JualDK+qpLP1TqDrejfR9IjEL3jYKV6XbY4ZSr4pSnFBtwe/
    OX03lq+8Qc0SFIgGJUo2K1Aryu+PFXAcGCoazulev9pXPABxQGimhJE7pvin1Czg
    sxYYyOnUN0nyQIYE1Rw30FvwW7oWaW3eXOK/oPUBl3dVEu6NkLw8aDHkY0xZsr7H
    oMB7ZFXfsRKY6i5oEs0mZviZopiPEuPPZdCswAp8PB1FpLu3PhVitnmZzFA0Wr8o
    aU0Iq7pWE7/IboAcmmtc7gV3w9+rVi+YHzO98k6e3JgihJj8Zx3eZRJiz/xDGaem
    B8bYYT7fOOQbkN2kFreUg8dJb37EQ1T9LbzoeNSRr4ccI4paGqOmyVZlU9sp0cSc
    niVPjeIUScH1/uHJOAFrP6fWMy76yMKkwBUF4P43jDfGDvn6mxraly2WB/5LcHCL
    Qm+nA9DdnM0mrTEVD3MVs/SiDu98omZSu+rAMoBCi9tx/u3a2pEd1rYWkwYAoeEU
    3IS+CXueE4It+xSIZoNFSquwzL2cHCVSgHR14PXWXSd8CBe9xlm+/t7BpH01sQvr
    l9UoB3vKDskiPOTiELzAHPTZi+leo2fZpT3E3yLNcG8u2JhFEPgSNinh5/1dERIL
    ylfp7iyTkYMJrpOh3KJ7jyF7KW3GWfJOa6gs+jc+kA==
    -----END CERTIFICATE-----
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: docker-registry
  labels:
    name: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  serviceName: docker-registry
  template:
    metadata:
      name: docker-registry
      labels:
        app: docker-registry
    spec:
      containers:
      - image: registry:2
        imagePullPolicy: IfNotPresent
        name: registry
        volumeMounts:
        - mountPath: /var/lib/registry
          name: registry-path
        - mountPath: /etc/docker/registry/config.yml
          name: config-path
          subPath: config.yml
        - mountPath: /etc/docker/registry/auth.cert
          name: auth-path
          subPath: auth.cert

      volumes:
      - name: registry-path
        hostPath:
            path: /opt/docker-registry
            type: Directory
      - name: config-path
        configMap:
          name: docker-registry
          items:
          - key: config.yml
            path: config.yml
      - name: auth-path
        configMap:
          name: docker-registry
          items:
          - key: auth.cert
            path: auth.cert

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-registry
  name: docker-registry
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30001
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: docker-registry
  type: NodePort
