apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-web-registry
  namespace: default
data:
  config.yml: |
    registry:
      # Docker registry url
      url: http://docker-registry:5000/v2
      # Docker registry fqdn
      name: 192.168.106.131:30001
      # To allow image delete, should be false
      readonly: false
      auth:
        # Enable authentication
        enabled: true
      # Token issuer, should equals to auth.token.issuer of docker registry
      issuer: 'my issuer'
      # Private key for token signing
      # certificate used on auth.token.rootcertbundle should signed by this key
      key: /conf/auth.key

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: docker-web-registry
  labels:
    name: docker-web-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-web-registry
  serviceName: docker-web-registry
  template:
    metadata:
      name: docker-web-registry
      labels:
        app: docker-web-registry
    spec:
      containers:
      - image: hyper/docker-registry-web:latest
        imagePullPolicy: IfNotPresent
        name: registry
        volumeMounts:
        - mountPath: /data
          name: data-path
        - mountPath: /conf/config.yml
          name: config-path
          subPath: config.yml
        - mountPath: /conf/auth.key
          name: auth-path
          subPath: auth.key

      volumes:
      - name: data-path
        hostPath:
          path: /opt/docker-registry-web
          type: Directory
      - name: config-path
        configMap:
          name: docker-web-registry
          items:
          - key: config.yml
            path: config.yml
      - name: auth-path
        configMap:
          name: docker-auth
          items:
          - key: auth.key
            path: auth.key
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-web-registry
  name: docker-web-registry
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30002
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: docker-web-registry
  type: NodePort
